[package]
name = "lachesis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
klotho = { path = "../klotho" }
async-std = { version = "1.10.0", features = ["attributes"] }
anyhow = "1.0.44"
